# Server configuration
hostPort: 8000
fileSystem: "./packs"

# Database configuration
database:
  user: s56601
  password: NjpPw0wYFUI1q7lx
  host: tools-db.tools.eqiad1.wikimedia.cloud
  port: "3306"
  name: scribe_server 


# local 
# database:
#   user: asif
#   password: newpassword
#   host: localhost
#   port: "3306"
#   name: scribe_server 