apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-scribe-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scribe-server
  template:
    metadata:
      labels:
        app: test-scribe-server
    spec:
      containers:
      - name: test-scribe-server
        image: tools-harbor.wmcloud.org/tool-testserver-scribe/test-scribe-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-scribe-server-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-scribe-server