name: pr_ci
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  ci:
    name: Run PR check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go get .

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          only-new-issues: true

      - name: Run tests
        run: make test
