name: Go Code Formatter

on: [push, pull_request]

jobs:
  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
