name: Go Code Formatter

on: [push, pull_request]

jobs:
  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Format code
        run: gofmt -w .

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git commit -m "Fix code formatting using gofmt"
            git push
          fi
